# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact_person', models.CharField(max_length=40)),
                ('contact_person_email', models.EmailField(max_length=254)),
                ('contact_person_phone', models.PositiveSmallIntegerField(default=0)),
                ('zip_code', models.PositiveIntegerField(default=0)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('house_number', models.PositiveSmallIntegerField(default=0)),
                ('house_floor', models.PositiveSmallIntegerField(default=0)),
                ('house_unit', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(error_messages={'required': 'Please enter your first name'}, max_length=30)),
                ('last_name', models.CharField(error_messages={'required': 'Please enter last name'}, max_length=30)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(error_messages={'invalid': 'Invalid email address', 'required': 'Please enter your email'}, max_length=254)),
                ('phone', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('password', models.CharField(error_messages={'required': 'Please enter a password'}, max_length=50)),
                ('zip_code', models.PositiveIntegerField()),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('street', models.CharField(blank=True, max_length=30, null=True)),
                ('house_number', models.PositiveSmallIntegerField()),
                ('house_floor', models.PositiveSmallIntegerField()),
                ('house_unit', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rokort.Club')),
            ],
        ),
    ]
