# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rokort', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='club',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
