# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rokort', '0006_auto_20160901_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'get_latest_by': 'created_at', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='boat',
            options={'get_latest_by': 'created_at', 'ordering': ['first_name']},
        ),
        migrations.AlterField(
            model_name='boat',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='boat',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='boat',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='boat',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='boat',
            name='zip_code',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
