# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rokort', '0007_auto_20160903_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='house_floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='house_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='house_unit',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='house_floor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='house_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
