# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rokort', '0008_auto_20160903_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='house_floor',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='house_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
