# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rokort', '0009_auto_20160903_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boat',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at', 'first_name']},
        ),
        migrations.AddField(
            model_name='boat',
            name='user_type',
            field=models.CharField(choices=[('club_admin', 'Administrator'), ('club_user', 'User'), ('system_user', 'System boat')], default='club_user', max_length=30),
        ),
    ]
